### ISSUE TITLE
font tag is deprecated in HTML5

### ISSUE THREAD

**Issue by ricealexander** [mferguson54100/Ticketing-System#1]
You use the font tag in tableQuery.php
The [font tag is deprecated](https://www.w3schools.com/tags/tag_font.asp) in HTML5

Instead of
```html
<td> <font face="Arial">First Name</font> </td>
```
you only need
```html
<td>First Name</td>
````

(If you really want Arial font, set the table's CSS to use Arial)

**Comment by mferguson54100** [comment]
Thanks fixed it
